### ISSUE TITLE
Unpublished tests

### ISSUE THREAD

**Issue by 11265** [DoranekoSystems/memory-server#3]
![屏幕截图 2024-06-20 145245](https://github.com/DoranekoSystems/memory-server/assets/53228826/b662c0a6-b5cb-44d8-a6ce-1a1bd1e22655)
When using patch on iOS, the terminal crashes immediately returning zsh:segmentationfault./memory-server, as if VirtualProtectEx failed: 87

**Comment by 11265** [comment]
![屏幕截图 2024-06-20 150107](https://github.com/DoranekoSystems/memory-server/assets/53228826/d94dc87a-493c-4045-a0f0-4a8f6072eaa6)
You can only use Data Type once. You cannot select Data Type when you use search for the second time.

**Comment by DoranekoSystems** [comment]
Thank you very much for confirming the operation.
It seems that the problem has probably been resolved.

**Comment by 11265** [comment]
In the jailbreak test patch, the program will flash back, and the jailbreak device does not have this problem.

**Comment by DoranekoSystems** [comment]
Probably could have fixed it.

**Comment by 11265** [comment]
without a Jailbroken iPhone13 ios17.4

**Comment by DoranekoSystems** [comment]
Does it happen even with the latest commit?

**Comment by 11265** [comment]
最新的提交完美
