### ISSUE TITLE
Search value type

### ISSUE THREAD

**Issue by 11265** [DoranekoSystems/memory-server#4]
Search for values ​​of type double and float in MemoryView Data Type
No such type, hope to adapt to double and float
![屏幕截图 2024-06-23 102420](https://github.com/DoranekoSystems/memory-server/assets/53228826/235d6336-2741-4ee1-9905-264aab03862c)

**Comment by DoranekoSystems** [comment]
Signed integer and float,double display implemented in memory view.

![img](https://github.com/DoranekoSystems/memory-server/assets/96031346/9870631f-a90d-41f4-a5e0-709ba2dc4865)
